TITLE Numero
.MODEL SMALL
.STACK 100H

.DATA
    MSG1 DB "DIGITE UM CARACTERE:$"
    SIM  DB 10,13,"O CARACTERE E UM NUMERO$"
    NAO  DB 10,13,"O CARACTERE NAO E UM NUMERO$"

.CODE
    MAIN PROC
    ;ACESSOS PARA AS VARIAVEIS 
    MOV AX,@DATA
    MOV DS,AX

    ;EXIBE MSG1
    MOV AH,9
    MOV DX,OFFSET MSG1
    INT 21H

    ;LE O CARACTERE DIGITADO/SALVA EM AL/MUDA PARA BL
    MOV AH,1
    INT 21H
    MOV BL,AL

    ;COMPARA COM 48(0 EM ASCII)
    CMP BL,48

    ;SE FOR MENOR QUE 48, VAI PARA LABEL NAONUM    
    JB NAONUM

    ;COMPARA COM 57(9 EM ASCII)
    CMP BL,57

    ;SE FOR MAIOR QUE 57, VAI PARA LABEL NAONUM  
    JA NAONUM

    ;EXIBE SIM
    MOV AH,9
    MOV DX,OFFSET SIM
    INT 21H

    ;PULA PRA AO FIM DO PROGRAMA 
    JMP FIM

    NAONUM:
        ;EXIBE NAO
        MOV AH,9
        MOV DX,OFFSET NAO
        INT 21H
    
    FIM:
        ;FIM DO POGRAMA
        MOV AH, 4CH
        INT 21H
    MAIN ENDP 
END MAIN

;ESSE PROGRAMA COMPARA O CARACTERE QUE VOCÊ DIGIOU COM 48 E 57, QUE SÃO 0 E 9 NA TEBELA ASCII, 
    ;SE FOR MENOR QUE 48, NÃO É UM NÚMERO 
    ;SE FOR MAIOR QUE 57, NÃO É UM NÚMERO 
    ; SE ESTRA ENTRE ESSES, O CARACTERE É UM NÚMERO 

